name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - master

jobs:
  build-and-analyze:
    name: Build and Analyze
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build, Test and Analyze with Maven
        # El comando es limpio, sin los parámetros -D
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        # Los secretos se definen de forma segura como variables de entorno
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
